# Generated by Django 4.0.3 on 2022-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='dateFirst',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='sportFirst',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
