# Generated by Django 3.2.9 on 2022-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='friendname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
