# Generated by Django 4.0.3 on 2022-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixcustomgroup',
            name='owner_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
