# Generated by Django 4.0.3 on 2022-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_name', models.CharField(blank=True, default='', max_length=50)),
                ('sche_date', models.CharField(blank=True, default='', max_length=50)),
                ('sche_memo', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
