# Generated by Django 4.0.3 on 2022-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteGroupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_group', models.CharField(blank=True, default='', max_length=50)),
                ('group', models.CharField(blank=True, default='', max_length=50)),
                ('invite_status', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
