# Generated by Django 4.0.3 on 2022-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='group_name')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sports', models.CharField(max_length=50)),
                ('friend_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
