# Generated by Django 4.0.3 on 2022-05-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
