# Generated by Django 4.0.3 on 2022-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_invitegroupgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='invite_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
