# Generated by Django 4.0.3 on 2022-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_customgroup_groupname_alter_customgroup_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='groupname',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
