# Generated by Django 4.0.3 on 2022-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_schegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schegroup',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
