# Generated by Django 4.0.3 on 2022-05-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_calendargroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendargroup',
            old_name='subm',
            new_name='subm2',
        ),
    ]
