# Generated by Django 4.0.3 on 2022-05-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_rename_subm_calendargroup_subm2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendargroup',
            old_name='subm2',
            new_name='csrfmiddlewaretoken',
        ),
    ]
