# Generated by Django 4.0.3 on 2022-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_customgroup_members_customgroup_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='friend_name',
            new_name='friendname',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='group_name',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='groupname',
            field=models.CharField(default='', max_length=200, verbose_name='groupname'),
        ),
    ]
