# Generated by Django 4.0.3 on 2022-05-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_rename_subm2_calendargroup_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendargroup',
            old_name='csrfmiddlewaretoken',
            new_name='smbb',
        ),
    ]
