# Generated by Django 4.0.3 on 2022-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_rename_friend_name_customgroup_friendname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='groupname',
            field=models.CharField(max_length=200, verbose_name='groupname'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='sports',
            field=models.CharField(default='', max_length=50),
        ),
    ]
