# Generated by Django 4.0.3 on 2022-05-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_remove_customgroup_username_customgroup_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='owner',
        ),
    ]
