# Generated by Django 4.0.3 on 2022-05-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_rename_csrfmiddlewaretoken_calendargroup_smbb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendargroup',
            old_name='smbb',
            new_name='csrfmiddlewaretoken',
        ),
    ]
