# Generated by Django 4.0.3 on 2022-05-18 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0005_alter_customgroup_groupname_alter_customgroup_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.ManyToManyField(blank=True, default='', related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
