# Generated by Django 4.0.3 on 2022-06-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_mixcustomgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixcustomgroup',
            name='members',
        ),
    ]
