# Generated by Django 4.0.3 on 2022-05-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_rename_smbb_calendargroup_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendargroup',
            old_name='csrfmiddlewaretoken',
            new_name='smb',
        ),
    ]
