# Generated by Django 4.0.3 on 2022-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_rename_csrfmiddlewaretoken_calendargroup_smb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendarGroup',
        ),
    ]
