# Generated by Django 4.0.3 on 2022-05-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_alter_daygroup_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daygroup',
            old_name='dates',
            new_name='myDates',
        ),
    ]
