# Generated by Django 4.0.3 on 2022-06-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_rename_dates_daygroup_mydates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='friendname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
